# Generated by Django 2.1.4 on 2019-01-19 18:24

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=True, upload_to=ecomapp.models.image_folder),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
